### ISSUE TITLE
Is there a way to add compiled plugins?

### ISSUE THREAD

**Issue by ofnuts** [flathub/org.gimp.GIMP#10]
Is there a generic way to add compiled plugins (about all non-python ones) such as resynthesizer, focus blur, liquid rescale, and GMIC to this?  (once they become available for 2.10 of course). Or should we wait for some benevolent person to contribute them either as additional flatpaks or as part of this one?

**Comment by TingPing** [comment]
It is pretty simple to add an extension point for plugins: https://tingping.github.io/2018/03/18/flatpaking-plugins.html

**Comment by Jehan** [comment]
Well yeah we can add flatpak extensions but I am not going to add non-official plug-ins as extension (because I don't have the time to maintain these).

But plug-ins can still be installed the same way as with any GIMP, which is: add your plug-ins in the personal plug-ins/ directory.
Of course, if your plug-in needs another library, as in your issue #9, that's a bit of a problem.

**Comment by ofnuts** [comment]
I notice that the Python runtime is specific to the flatpak, so any external modules added to the system Python aren't available in Gimp... Has anyone figured out a way to install modules from the Gimp python console or else?

**Comment by hfiguiere** [comment]
Resynthesizer is pending https://github.com/flathub/flathub/pull/1586
GMic is pending https://github.com/flathub/flathub/pull/1588

**Comment by hfiguiere** [comment]
LiquidRescale is pending too https://github.com/flathub/flathub/pull/1591

**Comment by Jehan** [comment]
The extension point has now been added to the flatpak and this is now live. Various plug-in manifests are still being reviewed but now we can say that the method exists. So let's close this! 🥳

**Comment by hfiguiere** [comment]
FocusBlur is now available on flathub.

$ flathub install org.gimp.GIMP.Plugin.FocusBlur
