### ISSUE TITLE
gimp flatpak not recognize regional language in ubuntu 18.04

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.gimp.GIMP#13]
Hello, I have installed ubuntu 18.04, and my regional language is Spanish. I followed the steps to install flatpak applications from Software Center of ubuntu 18.04.(https://flatpak.org/setup/Ubuntu/) I did not find gimp, however, I downloaded the flatpakref from the flathub page. After installing it, I started the application, but it is translated into English. I configured the application to the Spanish language from the gimp preferences, then I restarted the application, but the application is still in English.
I had installed linuxmint 18.3 (Spanish regional language) and I did not have this problem. It seems that it is something general because I installed other applications that I had in linuxmint 18.3 as mypaint, kdenlive, and I could not change the language to Spanish, after configuring them, in ubuntu 18.04.

**Comment by Jehan** [comment]
Thanks for the report.
Yeah flatpak does not install all languages by default. This is why when choosing another language in the Preferences of GIMP actually won't even work, simply because the language files are not even on your system. Yeah, I agree that it sucks.

This said, I believe that flatpak should detect your language and install the appropriate files. If it didn't, this is annoying. Nevertheless if you say this is a general problem, you should probably open a bug report to flatpak project, not here: https://github.com/flatpak/flatpak/issues/

In the meantime, a workaround to install all languages is to uninstall the locales then reinstall them! Yep that's pretty counter-intuitive, but since flatpak only installs part of the locales, it won't allow you to install them all unless you uninstall the pieces you have first:

> flatpak uninstall org.gimp.GIMP.Locale//stable
> flatpak install flathub org.gimp.GIMP.Locale//stable

Note: if you installed as --user, you might want to add this option here too.

How you ran these commands, I believe you should be able to set GIMP in Spanish through the Preferences as you'd expect.
Tell me how it went. :-)

**Comment by Jehan** [comment]
> Hi, thanks for all your help, but it did not work.

How exactly didn't it work? Did you have any error in the command line? If so, could you paste them?
Because I did test my commands and they worked (I have all the langs available in GIMP flatpak!). The part where I could see a problem in my command lines is the "flathub" name, since the repository could also be named differently for you. So that's why I am interested by any error you may have got.

> Regarding the general problem, I already reported it, but I am beginning to doubt that it really is general, since I installed, libreoffice, shotcut and these did recognize the regional language of my system well.

Ok. I found your upstream bug report. I'll paste it so that we can follow it: https://github.com/flatpak/flatpak/issues/1661

I don't think our flatpak manifest has anything related to language though. This is all very generic manifest and we let flatpak do its magics. But if the developers of flatpak think it comes from GIMP manifest, we welcome any fix to our manifest.

**Comment by Lvaskz** [comment]
At first I had some problems. Later I managed to install it, but when I wanted to configure them in Spanish from the preferences, it did not. The application is still in English.

**Comment by Jehan** [comment]
But did you run the 2 commands from above? If somehow flatpak failed to detect the correct localization at install, you need to run these commands to get all the languages:

> flatpak uninstall org.gimp.GIMP.Locale//stable
> flatpak install flathub org.gimp.GIMP.Locale//stable

**Comment by Lvaskz** [comment]
Yep, I ran the 2 commands.

**Comment by Lvaskz** [comment]
I will try again tonight, and I will paste something about terminal.

**Comment by Lvaskz** [comment]
Hi, I did again last night, I used 2 commands that you gave me. With the first one all work perfect, after I ran the second one and it installed all language. After I went to preferences of gimp and I select spanish language, all good until that. Gimp ask me refresh gimp or reload, I do. **But the app still in english**

**Comment by Jehan** [comment]
So no error messages with the 2 commands I gave you?

**Comment by Lvaskz** [comment]
NO, error messages with the commands. I will paste the image about output terminal in 2 hours.

**Comment by Lvaskz** [comment]
![captura de pantalla de 2018-05-14 20-46-24](https://user-images.githubusercontent.com/29207169/40086676-8f77ff1e-585c-11e8-8342-f058f8281ffe.png)

**Comment by Lvaskz** [comment]
here it is, sorry for delay

**Comment by Jehan** [comment]
> the only thing I've noticed is that gnome software asked me to update some things

Probably flatpak was in the list, wasn't it? There may have been a bug which was fixed recently and fixed all your flatpak apps.
Shall we close?
