### ISSUE TITLE
Gimp has distorted icons on the lower right side when using the flatpak version

### ISSUE THREAD

**Issue by uncivilgentleman** [flathub/org.gimp.GIMP#139]
Some icons on the lower right side of gimp are distorted in the Flatpak version of Gimp.

The problem is best shown not explained so I'll attach an image to this report. This is a rather old bug I just hadn't gotten around to reporting until now. It happens across distributions and on both Nvidia and Intel iGPU systems.

https://i.imgur.com/yVajG6G.png

**Comment by Jehan** [comment]
Yes, sorry I haven't answered earlier. It is an issue with GTK2 so it does happen on the whole 2.10 series when you shrink the docker width too much. Basically the workaround is to widen a bit the Layers dockable.

Bottom line I am aware of it, but I have doubt it will ever be fixed in the 2.10 series (I would not spend too much time on it at least). In the 2.99 dev series (future GIMP 3.0), this problem doesn't exist anymore.
