### ISSUE TITLE
Document a way to add Python modules to the built-in python

### ISSUE THREAD

**Issue by ofnuts** [flathub/org.gimp.GIMP#19]
Ass suggested by @Jehan , document a way to add usual Python libraries (those installed by `pip install`) to the flatpak runtime.

Attached a short Gimp script that uses the very popular `numpy`. The script is discussed [here](https://www.gimp-forum.net/Thread-Gimp-python-and-numpy).

[numpyops.zip](https://github.com/flathub/org.gimp.GIMP/files/2059807/numpyops.zip)

**Comment by Jehan** [comment]
Can't one simply add numpy library next to the plugin? I am pretty sure the `import numpy` will find a lib made available on the same directory (rather than installed system-wise).

This is different from how things used to work on GNU/Linux systems with package dependencies and stuff, but that is probably the only sure installation process actually.

**Comment by Nirei** [comment]
No, manually dumping whole python libraries next to each plugin that requires them **is not** an alternative to having a package manager for the integrated python. (??)

**Comment by ofnuts** [comment]
It appears that installing Python packages as "user" package using a system-wide Python v2 installation, and `pip install --user <package>` makes them also available to the Python runtime in the flatpak. This is OK for Python V2, because flatpak and system are very likely on the same version (2.7.17), but could be a bit touchy for Python v3 where the actual Python version is more varied (3.4 to 3.8).

**Comment by Jehan** [comment]
An extension point has now been added to the flatpak and this is now live. Various plug-in manifests are still being reviewed but now we can say that the method exists.

As for documenting, @hfiguiere said he would make a blog post about making extension for flatpak applications soon. In the meantime, looking at our manifest and the various extension manifest which were created should be already a good real-life docs by itself.

So far, only the manual extension got approved:
https://github.com/flathub/org.gimp.GIMP.Manual/

5 more manifests of plug-ins are still being reviewed, but I am expecting them to soon be accepted:
https://github.com/flathub/flathub/pull/1586
https://github.com/flathub/flathub/pull/1587
https://github.com/flathub/flathub/pull/1588
https://github.com/flathub/flathub/pull/1590
https://github.com/flathub/flathub/pull/1591

The manifest of these can already be looked at and serve as good doc sample for what a plug-in manifest requires.

Specifically to the Python case, the suggestion of @TingPing in #10 was interesting for a personal installation (though it is obviously not a real good generic solution) of upcoming GIMP 3 (since it is with `pip3`; `pip2` for Python 2 is not available in the stable flatpak):

```
flatpak run --command=pip3 org.gimp.GIMP install --user foo
```

Let's close for now because it will hard to do better short term, but we are always interested by simpler ways to install plug-ins in the GIMP flatpak if anyone tells us of better methods.
