### ISSUE TITLE
Why does gimp flatpak need `filesystems=host` permission?

### ISSUE THREAD

**Issue by Apacelus** [flathub/org.gimp.GIMP#209]
Any particular reasons for this flatpak have host access?

**Comment by Jehan** [comment]
Because GIMP doesn't use the file portal yet and this software is meant to work on files (imagine how useless would be GIMP if it were not allowed to open any file! What would be the point?).

Some day, we'll move on to the file portal (it's planned, but most likely after GIMP 3.0: https://gitlab.gnome.org/GNOME/gimp/-/issues/1830), then we'll be able to remove host access.

Hopefully it makes it clear so I can close this report. 😄
