### ISSUE TITLE
GIMP is default for open SVG - Bug

### ISSUE THREAD

**Issue by rolodoom** [flathub/org.gimp.GIMP#276]
I think this is a bug because GIMP is no a SVG editor. So if I have something like Inkscape installed, GIMP should not be setting the default mime type for SVG to GIMP on install. This is kind of annoying.

OS: Linux Manjaro kernel 6.6.8-2
Desktop: KDE Plasma 5.27.10
GIMP 2.10.36 Flatpak from Flathub

**Comment by Jehan** [comment]
This is the good old discussion about a concept of native formats or recommended formats or any other fine-grained software-format association in freedesktop specifications. Unfortunately the format only has a single [MimeType key](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-0.9.5.html#mime-types) and software are asked to just list all the format they somehow support.

Then when you have several software supporting the same formats, there are no notion of weighing priorities (it only depends on the order of file reading by default — possibly alphabetically? — then most desktop will have the feature to allow people to reorder the priority orders manually).

Anyway I already tried by the past to suggest new mimetypes in the desktop spec in order to handle exactly this kind of issues (which all the software have; it's not only GIMP with SVG; for instance another software which has XCF support could even get registered as first to open XCF files!) and have better default. A way to list our supported formats with a bit more subtlety (with concept of `NativeMimeType`, `IntentMimeType`, etc.). This proposition was unfortunately far from unanimous, didn't go anywhere and in the end, I didn't have the mental strength to push further.

So here we are.

Unfortunately I don't think that there is much more we can do at this point. The current state of file format and software association in Linux is that people have to reorder the association priorities when the defaults (which are random right now, because we just have no finer control on these) don't suit you.
