### ISSUE TITLE
Redirects issues of this tracker in favor of GIMP tracker

### ISSUE THREAD

**Issue by brunvonlope** [flathub/org.gimp.GIMP#294]
@Jehan @hfiguiere Please consider closing this tracker or add a bot to redirect the issues to the GIMP tracker at GitLab.

We have more contributors using flatpak at the official GIMP tracker, which makes easier to track flatpak specific bugs and the bugs wich aren't flatpak specific (e.g. no global menus).

**Comment by Jehan** [comment]
That's what I wanted to do a while back. After a search, I retrieved why I didn't do this in the end: https://github.com/flathub/flathub/issues/1046

> Note that I was proposed to close our bug tracker on github, which is not a bad idea, though it makes also for things a bit more messy. I like to have everything in the same place (this place being GNOME's gitlab).

So basically I didn't do this because otherwise the bug reports are further from the repository itself (my ideal situation being that repository should eventually move to our Gitlab instance, but this is what it is and GIMP cannot change this situation until Flathub makes it possible).

So yeah. Should we close the tracker here and redirect everyone to GNOME's Gitlab? I'm not against. I'd like to leave such a decision to @hfiguiere @novomesk and @HarryMichal, i.e. people who are helping the most here, mostly because I don't want to come back to a situation where I'm alone to work on this repo.

If everyone is happy to close our Github tracker and only use the Gitlab one for the flatpak issues, why not…

**Comment by hfiguiere** [comment]
The thing is if it is elsewhere then I surely won't follow the issues that are flatpak specific. I have way too much bugmail.

**Comment by brunolopesdsilv** [comment]
> The thing is if it is elsewhere then I surely won't follow the issues that are flatpak specific. I have way too much bugmail.

We have a specific Flatpak label. You can just subscribe to it:

![image](https://github.com/flathub/org.gimp.GIMP/assets/156703114/03968f69-a325-42c0-9124-9fca2ae90f8c)

**Comment by hfiguiere** [comment]
pass.

**Comment by brunolopesdsilv** [comment]
I don't understand the last message (can be interpreted in two ways). Considering that was about NOT redirecting issues... ok, we are very open mind with our packagers.

So, from my part, I will try to track this tracker additionally to the GIMP one to avoid duplicates. Hope that helps.

**Comment by Jehan** [comment]
I think that the global feeling is to leave things as-is for now.

In other news, I requested for your account to be added as a contributor on this repository @brunolopesdsilv : https://github.com/flathub/flathub/issues/5131

Globally the rules are the same as on our other repositories (autonomy while caring about others, etc.).
