### ISSUE TITLE
Update beta flatpak to Gnome 46

### ISSUE THREAD

**Issue by skierpage** [flathub/org.gimp.GIMP#334]
For what it's worth Inkscape is on org.gnome.Platform//46.
Thanks for all you do; onward to 3.0!

**Comment by brunvonlope** [comment]
@skierpage Thanks for reporting. I was planning to update the runtime to 46. But just to note, we don't update the runtime because some other flatpak is doing this, but because certain runtime is the latest version supported, which I don't know for sure.

---

So, I would like to know where we can find official info about the state of support of GNOME runtimes (which have some kind of lifespan as far I know), @Jehan. Do you know?

**Comment by hfiguiere** [comment]
one year from release. 45 will be EOL in October around when 47 is released.

**Comment by Jehan** [comment]
For info, it's already bumped in my GIMP 3.0RC1 MR: https://github.com/flathub/org.gimp.GIMP/pull/287

https://github.com/flathub/org.gimp.GIMP/pull/287/commits/f9ba9c38b95906d57df5deabc7dcacbf32fba050

**Comment by Jehan** [comment]
Oh and to answer your question, I'm not sure where to get detailed info on release versions (the [repo is here](https://gitlab.gnome.org/GNOME/gnome-build-meta) though), but if I recall, I think their maintenance policy is that they support N and N-1 (so up to one version late at a time).

And since GNOME is kinda following Fedora release cycle, i.e. a new version every 6 months, it indeed means support should stop about a year after release.

**Comment by brunvonlope** [comment]
Thank you everyone for the responses. I'm prone to updating things but the runtime is something too big to update right of the bat so it will take time...

... since I first read the changelogs and test the GIMP feature that uses some dep (I like to do this everytime I update a dep). So, let's hope that RC1 will caught me before I can complete this hobby.

**Comment by brunvonlope** [comment]
So, I diffed both 45 and 46 `manifest.json` comparing deps used by GIMP (not diffed the freedesktop runtimes). The main changes are regarding `glib` and `gobject-introspection`, which have changed the way they handle platform-specific GIO API and can impact our goat-exercises, specially the JavaScript one (to be tested).

`libjxl` also changed (its API) so I will test it to ensure that it is working well.

**Comment by brunvonlope** [comment]
Closing as solved

**Comment by skierpage** [comment]
Thanks everyone! After updating to latest org.gimp.GIMP//beta,
```
% flatpak remove --unused 
        ID                                            Branch          Op
 1. [-] org.freedesktop.Platform.ffmpeg-full          22.08           r
 2. [-] org.gnome.Platform                            45              r
 3. [-] org.gnome.Platform.Locale                     45              r
 4. [-] org.freedesktop.Platform.openh264             2.2.0           r
```
it freed up about 400MB+ on my clunky laptop.
