### ISSUE TITLE
Where is resynthesizer?

### ISSUE THREAD

**Issue by tkoop** [flathub/org.gimp.GIMP#346]
I installed this flatpak, which claims to come with Resythesizer, but I can't find it in the menu anywhere.

Shouldn't it be in Filters > Enhance > Resythesize, or maybe Filters > Maps > Heal selection?

Thanks.

**Comment by brunvonlope** [comment]
> which claims to come with Resythesizer

Where? 

As far I know, this is a 3P plug-in available as flatpak, we don't claim to have it inside the gimp flatpak.

**Comment by Jehan** [comment]
@tkoop Are you referring to this [news](https://www.gimp.org/news/2020/10/07/gimp-2-10-22-released/#plug-ins-and-manuals-in-flatpak-gimp)? What it says is not that the flatpak has resynthesizer by default. All our official packages are "vanilla" (i.e. that they only contain what the core GIMP provides, no more, no less) by default, but anyone is welcome to provide plug-ins to this flatpak in the form of "flatpak extensions".

And as it turns out, we already have a few such extensions (most maintained by @hfiguiere, if not all of them)?, and Resynthesizer is one of them. The news also gives the command line to install them, since Flathub doesn't have a GUI for flatpak extensions yet:

> flatpak install org.gimp.GIMP.Plugin.Resynthesizer

Note that some external package managers (such as GNOME Software) also show the extensions and allow you to install them from their GUI as well.

**Comment by hfiguiere** [comment]
note that for the beta (gimp soon to be 3.0) it should be installed with `flatpak install org.gimp.GIMP.Plugin.Resynthesizer//beta`

**Comment by brunvonlope** [comment]
No response of the original author. Flatpak mantainers comments, on the other hand, are clear enough that this isn't a bug.
