### ISSUE TITLE
The gimp is not working correctly in Endless OS 3.3.8

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gimp.GIMP#4]
[eos-diagnostic-180108_191632_UTC-0200.txt](https://github.com/flathub/org.gimp.GIMP/files/1613081/eos-diagnostic-180108_191632_UTC-0200.txt)

**Comment by LeandroStanger** [comment]
@nedrichards Could help

**Comment by Jehan** [comment]
Hello,

Could you tell me exactly which icons you are talking about? In the first image, I indeed see some icon which seems to be cut in the middle, but is it in GIMP? Which part is it?

In the second image, what image am I supposed to look at? The toolbox icons?
For information, you can update the icon sizes in Preferences > Interface > Icon Theme. In the bottom, change from "Guess Icon Size from resolution" to "Custom Icon Size".

Was that what you were looking for? If not, could you be more explicit with text explaining the issue. Thanks.

**Comment by nedrichards** [comment]
I can't see any images here @LeandroStanger I can only echo @Jehan if you let us know if that's the issue and if the mitigations he suggests worked then we can help further.

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-01-08 19-03-02](https://user-images.githubusercontent.com/26097419/34836176-31cb2d1c-f6de-11e7-9da4-a3295f27d92f.png)
![captura de tela de 2018-01-08 19-07-36](https://user-images.githubusercontent.com/26097419/34836175-319ab6be-f6de-11e7-9ee7-163169b0bca1.png)

**Comment by Jehan** [comment]
Thanks @LeandroStanger but that is still the same images. I need some explanation because I don't understand your problem. In the first image, I indeed see some weird icon, but as I said previously, I don't understand where this is taken from. If from GIMP, could you tell me where in GIMP this is?

The second image (which seems to already have disappeared but I saw it in the mail notification) looks all fine to me. Could you tell us what exactly is the problem you are pointing at?

**Please: use text!** :-)

Now maybe @nedrichards, you understand better what @LeandroStanger  meant with these images, if so, please explain me.

**Comment by LeandroStanger** [comment]
@nedrichards After I upgraded to Endless OS 3.3.8 the Gimp and LibreOffice applications and others are not unstable are all bugada
[eos-diagnostic-180111_173258_UTC-0200.txt](https://github.com/flathub/org.gimp.GIMP/files/1623883/eos-diagnostic-180111_173258_UTC-0200.txt)

**Comment by Jehan** [comment]
If that is about many application after Endless upgrade, it doesn't look like this is related to GIMP flatpak, isn't it?
