### ISSUE TITLE
add G'MIC plugin to gimp package

### ISSUE THREAD

**Issue by brettowe** [flathub/org.gimp.GIMP#40]
the G'MIC plugin ( https://gmic.eu/ ) has numerous plug-ins and is a massive addition to GIMP
not having G'MIC at this point feels like half of GIMP is missing.
due to it needing deps like FFT it doesn't dump into home plugin directories without extra work that feels like the flatpak should just deal with to begin with

**Comment by Jehan** [comment]
I am sorry, this won't happen. The GIMP flatpak is an official package (i.e. by the GIMP team). This means we will provide the software as full-featured as possible, and only from source maintained by the GIMP team. You could call it "vanilla GIMP".

To add a bit more info: providing third-party software is not an innocuous action. Doing so, we would take responsibility. Being a packager basically makes one a co-maintainer. The GIMP team is already too small for a huge project. We are not going to add any random third-party code to it, however famous or good they are (because yeah, G'Mic is good).

As for the base issue, there are 2 solutions currently in progress:

1. we should add an extension point for plug-ins (see #22): this is the cleaner solution, but has the disadvantage to be flatpak-only rather than generic, which is a problem for my ongoing project of an extension manager. We will most likely provide it anyway but I need to make the time some day for looking at provided code, review, fix and validate. Of course it won't mean G'Mic will become shipped with GIMP, but G'Mic developers will be free to create a flatpak package which can be integrated with GIMP flatpak.
2. and/or I am looking for a generic solution allowing to add libraries shipped with the plug-in itself (just as is done on Windows). It sucks, but is the most generic solution to work for any kind of distribution/package of GIMP on Linux.

Anyway closing as the shipping-together won't happen in any case.

**Comment by hfiguiere** [comment]
See https://github.com/flathub/flathub/pull/1588 - G'Mic will be available in Flatpak as an extension for GIMP
