### ISSUE TITLE
Add beta branch

### ISSUE THREAD

**Issue by eszlari** [flathub/org.gimp.GIMP#49]
https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

**Comment by Jehan** [comment]
I know, I read this blog post a few days ago, and thought it would be interesting for the future (a few months from now, hopefully). But why are you posting this link here without any explanation? We have no GIMP beta release right now, hence nothing to be done.

The post says it very clearly:

> This isn’t meant to be used for nightly builds, but for releases that has some level of testing and are expected to mostly work and be usable to non-developer end-users.

We don't have such things yet.
So I will close this report because this is not reddit here. ;-)
If I misunderstood something on what you wanted, please feel free to reopen the report and explain clearly. Thanks anyway!

**Comment by eszlari** [comment]
I was not sure, if you have read this blog post. So your plan is to add the beta branch, when there is a official 3.0 pre/alpha/beta release?

Since there is a AppImage now (https://discuss.pixls.us/t/experimental-appimage-package-for-the-gtk3-gimp-version/11496), I thought providing a test build would show people that flatpak is not lacking in that department.

**Comment by Jehan** [comment]
> So your plan is to add the beta branch, when there is a official 3.0 pre/alpha/beta release?

This should happen soon anywa.

Also I don't make the rules. Believe me, I would love to provide an official flatpak nightly build managed by flathub (it makes life so much simpler). But they don't have such "nightly channel" and explicitly forbid to use the beta channel as-is (this is written black on white on the post; probably because they knew people would just want to do this as a first thought). So there is nothing I can do.

Also:

> Since there is a AppImage now, I thought providing a test build would show people that flatpak is not lacking in that department.

I maintain this flatpak because I think this is a good technology and such package was seriously missing for Linux users. But I don't do a competition. I am not trying to be better than AppImage or any other format and don't care proving that "flatpak is not lacking". So I would love to have a nightly channel… because I would love for us to be able to provide easy nightly builds on Linux (not because I want to compete with some other package). That's all. :-)

For what is worth, we have even been in discussion with the AppImage and the Snap maintainers to have their builds as official GIMP builds too (main reason why this is not going forward is because it's hard to talk with them as they don't come on IRC to participate to the life of the software with everybody). And I, for one, would really be happy if we could provide officially these other packages because some people prefer them (then future will tell if one format will end up mostly used; I bet on flatpak, but I may be wrong and personally I don't care much if I am; the end goal is to have a good software environment for people on Linux, not to make wars between software).

That's it for my opinion on the showing flatpak is not lacking.

P.S.: also for the record, I have a private nightly flatpak repository of GTK+3 GIMP (and I have had it since May 2018, so it's not new stuff!) and the manifest for this is maintained in the official GIMP repository (under `build/flatpak/`). So there is nothing to prove by the way. It works and exists. Simply I can't make this public because, as said, flathub doesn't have a nightly channel (and *ZeMarmot* can't afford a proper server just to demo flatpak; demoing technologies is not what we do).

**Comment by eszlari** [comment]
> (then future will tell if one format will end up mostly used; I bet on flatpak, but I may be wrong and personally I don't care much if I am; the end goal is to have a good software environment for people on Linux, not to make wars between software)

I could agree with that, if it wasn't the case, that Canonical controls the only snap repository.

**Comment by eszlari** [comment]
> Simply I can't make this public because, as said, flathub doesn't have a nightly channel (and ZeMarmot can't afford a proper server just to demo flatpak; demoing technologies is not what we do).

Why dont't you ask the GNOME project to add GIMP to the `gnome-apps-nightly` flatpak repository:
https://wiki.gnome.org/Apps/Nightly

**Comment by Jehan** [comment]
Last I asked, I was being told that the whole nightly apps were already taking a long time to be built, so it was not sure if we could make use of the nightly infrastructure (we are not a GNOME app, so we don't have the right by default). Though considering the history, I was told maybe an exception could be made. To be discussed. But that was a long time ago. Maybe things changed, and I haven't followed up with my request again for many months now. Maybe now rules changed even, and/or they would accept directly, I don't know.

But really the big reason is that I can't make the time to deal with a nightly on yet another infrastructure. I maintain this flatpak because I think it is highly needed, but I don't have any big pleasure doing it. I like to maintain code, not builds. To be fair, we don't even use this flatpak, because in our studio, we have our custom builds of GIMP, with newer code, sometimes a bit experimental code too, and it's full featured (flatpak still has a few shortcomings unfortunately). I only consider the flatpak needed for the ones who won't build themselves and would still appreciate the last version of GIMP, so I only do it for the good of the community. And that's still a lot of work.

Even the stable flatpak (which is 1000x more important that a nightly) is still not perfect (look at the 2 pull requests for instance; they are improvements I started and didn't finish yet because I can't make the time).

**BUT** this is Free Software. If someone wishes to contribute maintenance of a build to the `gnome-apps-nightly`, please be my guest! Get the permission for GIMP, prepare whatever has to be prepared, just make sure everything is transparent and well documented (conditions to be an official build), and maintain the build. If you can do this, you don't have to wait for me. I have a gazillion other stuff I need to take care of first. :-D
I am not holding tight the maintainer hat and would really welcome contributions with warm heart. 💟

**Comment by eszlari** [comment]
Don't you think it would make sense to leave this issue open until the first preview build is released? So that people don't miss what you have written here?

**Comment by Jehan** [comment]
Not sure how useful it is, but whatever. Let's leave open.

**Comment by BrainBlasted** [comment]
@Jehan regarding a nightly flatpak, including a flatpak setup in-repo could help you with development.
Most GNOME apps use a flatpak setup for development, and it's great for a few reasons:

* Nobody needs to download development dependencies themselves. All you need to get started is flatpak itself and, in our case, GNOME Builder.

* If dual installation as described [here](https://gitlab.gnome.org/GNOME/Initiatives/wikis/DevOps-with-Flatpak#parallel-installation) is set up, you can run the development version in parallel to the stable version. For users this means they can install the development versions without replacing the stable version if they rely on GIMP.

Depending on what shortcomings you run into with flatpak we might be able to get those solved, especially on the GTK3 version.

**Comment by Jehan** [comment]
> including a flatpak setup in-repo could help you with development.

As already said in my second comment, we have a working flatpak manifest available in the master branch. See in `build/flatpak/`. This has been available for more than 2 years according to git log.

> Depending on what shortcomings you run into with flatpak we might be able to get those solved, especially on the GTK3 version.

We welcome any patch or improvement, to core GIMP code, as well as on the flatpak. Please feel free.

**Comment by hfiguiere** [comment]
There is currently a beta branch. This can be closed.

**Comment by Jehan** [comment]
> There is currently a beta branch. This can be closed.

Yeah I know, but shh it's a secret. 🤫

More seriously, I made a mistake and was not planning on publishing the branch just yet. I wanted the first publication to be for 2.99.2 (which might be tomorrow anyway!). But just creating the branch on github ran a build and published it (this is kind of a limitation of the Flathub system though it happens only once, so…). So **officially** there is still no beta branch even if there is one… 🙄

Very soon (tomorrow if our plan does not fall through, as said), there will be one with an actual dev release, then I'll close this report. :-)

**Comment by hfiguiere** [comment]
Fair enough. So I'll if I can have plugin support for 2.99.

**Comment by Jehan** [comment]
Awesome! 👍

**Comment by Jehan** [comment]
For info, we pushed back 2.99.2 for at least a week (next week-end) so you still have time.

Of course this can also happen later, and anyway most big plug-ins don't have GIMP 3 API support yet. So no rush.

**Comment by Jehan** [comment]
The beta branch now officially exists.
