### ISSUE TITLE
Plugins, icons and other stuff

### ISSUE THREAD

**Issue by caarlosfuentes** [flathub/org.gimp.GIMP#72]
Hi, i have installed by Flatpak gimp2.10 in my Ubuntu 18-04, generally if i want install a plugin, i download the plugin and put into the folder plugins, but it doesn't work. I mean i go to the path in /home/myuser/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins, put the plugin, i open gimp then not plugin, same for icons, themes...etc. maybe there is something i do wrong, can help me please

**Comment by Jehan** [comment]
In GIMP flatpak, we have this small particularity that if you already had a config directory for GIMP (i.e. if `$XDG_CONFIG_HOME/GIMP/2.10/`, defaulting to `$HOME/.config/GIMP/2.10/`, exists), then we uses this folder. This was so that GIMP users don't lose all their configuration, icons, themes, data, plug-ins and whatnot.

But it's also true that the fact that it reverts to the flatpak defaults `$HOME/.var/app/<id>` when people didn't have a pre-existing config folder is very confusing. I was against this decision (I wanted that our flatpak just uses our standard folder, always, without condition ⇒ no confusion) from the flatpak project but it still went in.

So you should check, it's probably the problem you have if you were already using GIMP before trying the flatpak version.

For plug-ins, some may still not work as we have some issues with advanced plug-ins requiring dependencies not available in the flatpak environment (cf. #22). So plug-ins like G'MIC won't run in Flatpak GIMP for instance, unfortunately. Simpler plug-ins will run fine.
And icons, themes, data and the like will definitely be picked up fine.

**Comment by Jehan** [comment]
Ok let's close this. I believe this has been answered.

If my answer was not exactly what you encountered, please feel free to reopen.
