### ISSUE TITLE
Fourier plugin doesn't work.

### ISSUE THREAD

**Issue by ofnuts** [flathub/org.gimp.GIMP#9]
Additional clue: while starting Gimp:

    /home/me/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/fourier: error while loading shared libraries: libfftw3.so.3: cannot open shared object file: No such file or directory

**Comment by ofnuts** [comment]
Yes and no... yes it's third party, but the `fourier` executable is included in the flatpak, I didn't add it. So if it's included it should be made to work, or removed. The flatpak also includes the wavelet decomposition, which used to be a 3rd party plugin...

**Comment by Jehan** [comment]
Is it? I have not added any non-default (third-party) plug-in.
You can read the full list of included things in:
https://github.com/flathub/org.gimp.GIMP/blob/master/org.gimp.GIMP.base-modules.json
https://github.com/flathub/org.gimp.GIMP/blob/master/org.gimp.GIMP.app-modules.json

Are you sure you didn't have this plug-in previously installed in your config directory?
As for wavelet-decompose, this is something else. This plugin has actually been added in the GIMP main tree (written from scratch, apparently if I read the commits well). So finding it there is normal.

**Comment by Jehan** [comment]
For the record, I tested trying to add a library with plug-ins. As expected, it did not work well. That sort of things works on Windows, but Linux…

**Comment by ofnuts** [comment]
Sorry, my mistake. That FFT plugin was the lone plugin installed manually. This said, importing plugins that won't work may not be a good idea.

**Comment by Jehan** [comment]
Thanks for checking.
Unfortunately in the current state of the plug-in code, we have not much solution: we can't really know for sure if the import will work. So we just do it, because on the other hand, if we don't (while in some cases it would work), some people would resent us for having "lost" their plug-ins. :-/
We never really win.

I am planning on improving the plug-in situation for GIMP 3. But for compatibility reason, no improvement can happen in 2.10.x.

**Comment by hfiguiere** [comment]
If you tell me which plugin you are talking about (Link please) I can see if it can be package as a flatpak as I'm working on extension support.

**Comment by Jehan** [comment]
@hfiguiere Feel free to reopen this report if you wish to package the plug-in as an extension.

**Comment by hfiguiere** [comment]
Sure but I can't find it. Hence me asking for a link.

**Comment by Jehan** [comment]
Is it this: https://www.lprp.fr/gimp_plugin_en/ ? (found via: https://www.reddit.com/r/GIMP/comments/al0nfd/does_anybody_have_the_fast_fourier_transform_fft/)

**Comment by Jehan** [comment]
Some distributions are using this URL: https://github.com/pixlsus/registry.gimp.org_static/blob/master/registry.gimp.org/files/fourier-0.4.3-2.tar.gz?raw=true (from a static backup of our old registry, which doesn't make the tarball more trustworthy as anyone was able to post there whatever they wanted, which is why we ended up discontinuing it; but anyway you could make some basic checks).

Anyway let's reopen now. Why not. 🙂

**Comment by hfiguiere** [comment]
> Is it this: https://www.lprp.fr/gimp_plugin_en/ ? (found via: https://www.reddit.com/r/GIMP/comments/al0nfd/does_anybody_have_the_fast_fourier_transform_fft/)

That website was broken when I tried.

**Comment by Jehan** [comment]
Well… now it works. 🤷

I'm excited of all the cool plug-ins which will land in GIMP-land hopefully very soon! 🥳

**Comment by hfiguiere** [comment]
I meant when I tried a few days ago. Anyway, I'll give a look at it later.

**Comment by Jehan** [comment]
Yeah no hurry.

**Comment by hfiguiere** [comment]
it is now available on flathub as org.gimp.GIMP.Plugin.Fourier

**Comment by hfiguiere** [comment]
(this can be closed)

**Comment by Jehan** [comment]
Awesome, thanks!
